# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: 'github-actions'
    # Workflow files stored in the default location of `.github/workflows`. (You don't need to specify `/.github/workflows` for `directory`. You can use `directory: "/"`.)
    directory: '/'
    schedule:
      interval: 'monthly'
    assignees:
      - 'emackie-eddaic'
    reviewers:
      - 'emackie-eddaic'
  - package-ecosystem: 'npm' # See documentation for possible values
    directory: '/' # Location of package manifests
    schedule:
      interval: 'monthly'
    assignees:
      - 'emackie-eddaic'
    reviewers:
      - 'emackie-eddaic'
    commit-message:
      prefix: 'feat'
      prefix-development: 'chore'
      include: 'scope'
    ignore:
      # For all packages, ignore all patch and major updates
      - dependency-name: '*'
        update-types: ['version-update:semver-major']
    groups:
      jest:
        patterns:
          - '@types/jest'
          - 'jest'
      nestjs:
        patterns:
          - '@nestjs/common'
          - '@nestjs/testing'
      prettier:
        patterns:
          - 'eslint-config-prettier'
          - 'eslint-plugin-prettier'
          - 'prettier'
      typescript-eslint:
        patterns:
          - '@typescript-eslint/*'
